/* Auto-generated by genmsg_cpp for file /home/francescow/Downloads/V-REP_PRO_EDU_V3_1_0/programming/ros_stacks/vrep/vrep_common/srv/simRosStartSimulation.srv */
#ifndef VREP_COMMON_SERVICE_SIMROSSTARTSIMULATION_H
#define VREP_COMMON_SERVICE_SIMROSSTARTSIMULATION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace vrep_common
{
template <class ContainerAllocator>
struct simRosStartSimulationRequest_ {
  typedef simRosStartSimulationRequest_<ContainerAllocator> Type;

  simRosStartSimulationRequest_()
  {
  }

  simRosStartSimulationRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::vrep_common::simRosStartSimulationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrep_common::simRosStartSimulationRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct simRosStartSimulationRequest
typedef  ::vrep_common::simRosStartSimulationRequest_<std::allocator<void> > simRosStartSimulationRequest;

typedef boost::shared_ptr< ::vrep_common::simRosStartSimulationRequest> simRosStartSimulationRequestPtr;
typedef boost::shared_ptr< ::vrep_common::simRosStartSimulationRequest const> simRosStartSimulationRequestConstPtr;



template <class ContainerAllocator>
struct simRosStartSimulationResponse_ {
  typedef simRosStartSimulationResponse_<ContainerAllocator> Type;

  simRosStartSimulationResponse_()
  : result(0)
  {
  }

  simRosStartSimulationResponse_(const ContainerAllocator& _alloc)
  : result(0)
  {
  }

  typedef int32_t _result_type;
  int32_t result;


  typedef boost::shared_ptr< ::vrep_common::simRosStartSimulationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrep_common::simRosStartSimulationResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct simRosStartSimulationResponse
typedef  ::vrep_common::simRosStartSimulationResponse_<std::allocator<void> > simRosStartSimulationResponse;

typedef boost::shared_ptr< ::vrep_common::simRosStartSimulationResponse> simRosStartSimulationResponsePtr;
typedef boost::shared_ptr< ::vrep_common::simRosStartSimulationResponse const> simRosStartSimulationResponseConstPtr;


struct simRosStartSimulation
{

typedef simRosStartSimulationRequest Request;
typedef simRosStartSimulationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct simRosStartSimulation
} // namespace vrep_common

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosStartSimulationRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosStartSimulationRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::vrep_common::simRosStartSimulationRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::vrep_common::simRosStartSimulationRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::vrep_common::simRosStartSimulationRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosStartSimulationRequest";
  }

  static const char* value(const  ::vrep_common::simRosStartSimulationRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vrep_common::simRosStartSimulationRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
\n\
\n\
\n\
";
  }

  static const char* value(const  ::vrep_common::simRosStartSimulationRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::vrep_common::simRosStartSimulationRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosStartSimulationResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosStartSimulationResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::vrep_common::simRosStartSimulationResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const  ::vrep_common::simRosStartSimulationResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::vrep_common::simRosStartSimulationResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosStartSimulationResponse";
  }

  static const char* value(const  ::vrep_common::simRosStartSimulationResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vrep_common::simRosStartSimulationResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 result\n\
\n\
\n\
";
  }

  static const char* value(const  ::vrep_common::simRosStartSimulationResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::vrep_common::simRosStartSimulationResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vrep_common::simRosStartSimulationRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct simRosStartSimulationRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vrep_common::simRosStartSimulationResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.result);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct simRosStartSimulationResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<vrep_common::simRosStartSimulation> {
  static const char* value() 
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const vrep_common::simRosStartSimulation&) { return value(); } 
};

template<>
struct DataType<vrep_common::simRosStartSimulation> {
  static const char* value() 
  {
    return "vrep_common/simRosStartSimulation";
  }

  static const char* value(const vrep_common::simRosStartSimulation&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<vrep_common::simRosStartSimulationRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const vrep_common::simRosStartSimulationRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<vrep_common::simRosStartSimulationRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosStartSimulation";
  }

  static const char* value(const vrep_common::simRosStartSimulationRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<vrep_common::simRosStartSimulationResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const vrep_common::simRosStartSimulationResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<vrep_common::simRosStartSimulationResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosStartSimulation";
  }

  static const char* value(const vrep_common::simRosStartSimulationResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_SERVICE_SIMROSSTARTSIMULATION_H

